
input_rep: !BertBaseCase
output_rep: !BertBaseCase

logging: !Logger
    output_dir: /tmp
    log_file: test.txt
    overwrite: True

model: !BaseModel
    emb_dim: 32

opt: !Adam
    lr: !!float 1e-4
    betas: !!python/tuple [0.9, 0.98]
    eps: !!float 1e-9

train_dl: !DataLoader
    dataset: !CommonGen
        split: "train"
    batch_size: 256
    shuffle: True
    drop_last: True

test_dl: !DataLoader
    dataset: !CommonGen
        split: "validation"
    batch_size: 128
    shuffle: True
