
input_rep: !TTTBoardRep
output_rep: !TTTMoveRep

logging: !Logger
    output_dir: /tmp
    log_file: test_yaml.txt
    overwrite: True

model: !BaseModel
    emb_dim: 128
    load: /tmp/model_3.pth

opt: !Adam
    lr: !!float 1e-4
    betas: !!python/tuple [0.9, 0.98]
    eps: !!float 1e-9

train_data: !DataLoader
    dataset: !TTTData
        path: ./data/ttt_easy_train.csv 
    batch_size: 128
    shuffle: True
    drop_last: True

test_data: !DataLoader
    dataset: !TTTData
        path: ./data/ttt_easy_test.csv 
    batch_size: 128
    shuffle: True
